/*
 * NEC XON (c) Copyright 2025.
 *
 * Backup catalogue for the Administrator Portal's Backup page.
 *
 * The mediator does not take backups. It shares the ./backups directory with
 * the bkm-backup container and reports what it finds there, and an on-demand
 * run is requested by dropping a trigger file that bkm-backup is watching for.
 *
 * That indirection is deliberate. Doing the dumps here would mean either giving
 * the mediator the Docker socket or duplicating every database credential into
 * a process that also serves HTTP to the portal and to phones. The backup
 * engine has no listening port at all, and this is the only thing that can ask
 * it to do anything - and all it can ask for is "run".
 *
 * Everything here reads the filesystem rather than trusting status.json alone:
 * a status file saying "ok" next to a directory with no archives in it is the
 * exact failure mode a backup page exists to catch.
 */
'use strict';

const { Router } = require('express');
const fs         = require('fs');
const path       = require('path');
const logger     = require('../logger');

const router = Router();

const BACKUP_DIR = process.env.BACKUP_DIR || '/backups';

// How old the newest archive may be before the page stops calling it healthy.
// Default 36h, which covers a daily schedule plus a missed run.
const STALE_HOURS = parseInt(process.env.BACKUP_STALE_HOURS || '36', 10);

// Archive names are generated by backup.sh, never by a user. Anything not
// matching this exactly is refused rather than sanitised, so no request can
// walk out of the backup directory and stream, say, /project/.env.
const ARCHIVE_RE = /^vitallink-\d{8}_\d{6}\.tar\.gz$/;

function readStatus() {
  try {
    return JSON.parse(fs.readFileSync(path.join(BACKUP_DIR, 'status.json'), 'utf8'));
  } catch (e) {
    return null;
  }
}

// A request that the engine has not picked up yet. It polls every few seconds,
// so between the button press and the run actually starting, status.json still
// describes the PREVIOUS run - which would otherwise look like "idle" and let a
// second request through.
function requestPending() {
  try {
    fs.accessSync(path.join(BACKUP_DIR, '.run-now'));
    return true;
  } catch (e) {
    return false;
  }
}

function listArchives() {
  let names;
  try {
    names = fs.readdirSync(BACKUP_DIR);
  } catch (e) {
    return null; // directory missing entirely - the engine was never started
  }
  return names
    .filter((n) => ARCHIVE_RE.test(n))
    .map((name) => {
      const st = fs.statSync(path.join(BACKUP_DIR, name));
      let sha = null;
      try {
        sha = fs.readFileSync(path.join(BACKUP_DIR, name + '.sha256'), 'utf8').trim();
      } catch (e) { /* sidecar is optional */ }
      return {
        name,
        bytes: st.size,
        createdAt: st.mtime.toISOString(),
        ageHours: Math.round((Date.now() - st.mtimeMs) / 36e5 * 10) / 10,
        sha256: sha,
      };
    })
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt));
}

router.get('/status', (req, res) => {
  const archives = listArchives();
  const last = readStatus();

  if (archives === null) {
    return res.json({
      health: 'down',
      engineUp: false,
      checkedAt: new Date().toISOString(),
      detail: `${BACKUP_DIR} is not readable. The bkm-backup container is not ` +
              'running, or ./backups is not mounted into the mediator.',
      archives: [],
    });
  }

  const newest = archives[0] || null;
  const pending = requestPending();
  const running = !!(last && last.state === 'running');

  // The verdict comes from the archives on disk first and the status file
  // second. "No backup at all" and "the last run failed" are different problems
  // and the page says which.
  let health = 'ok';
  let detail = '';
  if (!newest) {
    health = 'down';
    detail = 'No backup has ever completed on this server.';
  } else if (newest.ageHours > STALE_HOURS) {
    health = 'down';
    detail = `The newest backup is ${Math.round(newest.ageHours)} hours old. ` +
             'Scheduled backups are not running.';
  } else if (last && last.state === 'failed') {
    health = 'warn';
    detail = 'The last run did not complete: ' + (last.error || 'no reason recorded');
  } else if (running || pending) {
    health = 'ok';
    detail = running ? 'A backup is running now.' : 'A backup has been requested.';
  }

  res.json({
    health,
    engineUp: true,
    running,
    pending,
    checkedAt: new Date().toISOString(),
    detail,
    staleAfterHours: STALE_HOURS,
    schedule: (last && last.schedule) || '',
    keep: (last && last.keep) || null,
    last: last || null,
    newest,
    archives,
    totalBytes: archives.reduce((sum, a) => sum + a.bytes, 0),
  });
});

/*
 * POST /backup/run - ask bkm-backup to take one now.
 *
 * Returns 202, not 200: the archive does not exist yet when this replies. The
 * page polls /status and watches the run go from "running" to a new archive,
 * which is also what proves to the operator that the schedule works.
 */
router.post('/run', (req, res) => {
  const last = readStatus();
  if (last && last.state === 'running') {
    return res.status(409).json({
      ok: false,
      error: 'a backup is already running',
      startedAt: last.startedAt,
    });
  }
  if (requestPending()) {
    return res.status(409).json({
      ok: false,
      error: 'a backup has already been requested',
      detail: 'The engine has not picked it up yet. Give it a few seconds.',
    });
  }

  try {
    fs.writeFileSync(path.join(BACKUP_DIR, '.run-now'), new Date().toISOString());
    logger.info({ event: 'backup-run-requested' });
    return res.status(202).json({
      ok: true,
      note: 'Requested. The engine picks this up within about 5 seconds.',
    });
  } catch (e) {
    logger.error({ event: 'backup-run-request-failed', error: e.message });
    return res.status(503).json({
      ok: false,
      error: 'could not reach the backup engine',
      detail: `${BACKUP_DIR} is not writable: ${e.message}`,
    });
  }
});

router.get('/manifest/:name', (req, res) => {
  const name = req.params.name;
  if (!ARCHIVE_RE.test(name)) return res.status(400).json({ error: 'bad archive name' });
  const file = path.join(BACKUP_DIR, name.replace(/\.tar\.gz$/, '.manifest.txt'));
  fs.readFile(file, 'utf8', (err, text) => {
    if (err) return res.status(404).json({ error: 'no manifest for this archive' });
    res.type('text/plain').send(text);
  });
});

/*
 * GET /backup/download/:name - stream an archive to the administrator.
 *
 * This is how a single-server deployment gets a copy OFF the server, which is
 * the whole point: an archive sitting on the same disk as the database does not
 * survive losing that disk. It is also why the archive is worth guarding - it
 * contains every patient record and, unless BACKUP_INCLUDE_ENV is false, the
 * deployment's credentials.
 */
router.get('/download/:name', (req, res) => {
  const name = req.params.name;
  if (!ARCHIVE_RE.test(name)) return res.status(400).json({ error: 'bad archive name' });

  const file = path.join(BACKUP_DIR, name);
  fs.stat(file, (err, st) => {
    if (err || !st.isFile()) return res.status(404).json({ error: 'no such archive' });
    logger.info({ event: 'backup-download', archive: name, bytes: st.size });
    res.setHeader('Content-Type', 'application/gzip');
    res.setHeader('Content-Length', st.size);
    res.setHeader('Content-Disposition', `attachment; filename="${name}"`);
    const stream = fs.createReadStream(file);
    stream.on('error', (e) => {
      logger.error({ event: 'backup-download-failed', error: e.message });
      res.destroy();
    });
    stream.pipe(res);
  });
});

module.exports = router;
