connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://db-postgres:5432/dhis2
connection.username = admin
connection.password = password123
connection.pool.max_size = 20
