#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# reseed_mafeteng.sh — provision the 18 real Mafeteng facilities (+ users + stock)
#
# Replaces the Maseru demo with Mafeteng district. ADDITIVE + IDEMPOTENT: it
# upserts everything (safe to re-run); it does NOT hard-delete — Maseru clinics are
# only DEACTIVATED (set REMOVE_MASERU=0 to skip even that).
#
# Driven by config/facilities/mafeteng-seed-data.env (generated by
# scripts/gen_mafeteng_configs.py from config/facilities/mafeteng-facilities.json).
#
# Run ON THE DOCKER HOST (uses localhost service ports + `docker exec` to the DBs).
#   DRY_RUN=1 bash scripts/reseed_mafeteng.sh      # show what would happen, no writes
#   bash scripts/reseed_mafeteng.sh                # apply
# Override endpoints/creds via env if your ports differ.
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail
cd "$(dirname "$0")/.."

# ── Config (override via env) ────────────────────────────────────────────────
LMIS_PASSWORD="${LMIS_PASSWORD:-password}"
KC_ADMIN_PASSWORD="${KC_ADMIN_PASSWORD:-admin}"
DHIS2_PASSWORD="${DHIS2_PASSWORD:-district}"
PROGRAM_ID="${PROGRAM_ID:-31ef5fd8-cef9-4ec0-8304-3018d2cf6c9c}"
GEO_LEVEL_DISTRICT_ID="${GEO_LEVEL_DISTRICT_ID:-2b01de8b-cc0f-4e2f-9fa3-2a7e0d1d9876}"
GEO_ZONE_COUNTRY_ID="${GEO_ZONE_COUNTRY_ID:-c1e921a6-f37f-4a4c-89e3-f3e25f2b3a01}"
DHIS2_OU_NATIONAL="${DHIS2_OU_NATIONAL:-LesNatOrg01}"
REMOVE_MASERU="${REMOVE_MASERU:-1}"
DRY_RUN="${DRY_RUN:-0}"
STOCK_QTY="${STOCK_QTY:-1000}"

# ── Auto-detect endpoints from the running containers ────────────────────────
# Works on any host where the stack is up (local OR prod) regardless of how ports
# are published. Uses the container's published host port, falling back to the
# base-compose default. Override any with the matching env var (LMIS_URL=, KC_URL=,
# DHIS2_URL=, HAPI=, LMIS_DB=, LMIS_NGINX=) if your container names differ.
_hostport() { docker port "$1" "$2" 2>/dev/null | head -1 | sed 's/0\.0\.0\.0/localhost/;s/127\.0\.0\.1/localhost/'; }
_url()      { local hp; hp="$(_hostport "$1" "$2")"; echo "http://${hp:-$3}"; }
LMIS_DB="${LMIS_DB:-$(docker ps --format '{{.Names}}' 2>/dev/null | grep -E 'openlmis.*-db' | head -1)}"
LMIS_DB="${LMIS_DB:-openlmis-ref-distro-db-1}"
LMIS_NGINX="${LMIS_NGINX:-$(docker ps --format '{{.Names}}' 2>/dev/null | grep -E 'openlmis.*nginx' | head -1)}"
LMIS_URL="${LMIS_URL:-$(_url "${LMIS_NGINX:-openlmis-ref-distro-nginx-1}" 80 localhost:8082)}"
KC_URL="${KC_URL:-$(_url keycloak 8080 localhost:8083)}"
DHIS2_URL="${DHIS2_URL:-$(_url dhis2-web 8080 localhost:8081)}"
HAPI="${HAPI:-$(_url hapi-fhir 8080 localhost:18079)/fhir}"
TODAY="$(python3 -c 'from datetime import datetime,timezone;print(datetime.now(timezone.utc).strftime("%Y-%m-%d"))')"

log()  { echo "[reseed] $*"; }
run()  { if [[ "$DRY_RUN" == "1" ]]; then echo "  DRYRUN: $*"; else eval "$@"; fi; }
psqlc() { docker exec "$LMIS_DB" psql -U postgres -d open_lmis -t -c "$1" 2>/dev/null | tr -d '[:space:]'; }
psqlq() { if [[ "$DRY_RUN" == "1" ]]; then echo "  DRYRUN psql: ${1:0:80}..."; else docker exec "$LMIS_DB" psql -U postgres -d open_lmis -q -c "$1" >/dev/null 2>&1; fi; }

source config/facilities/mafeteng-seed-data.env

# ── Tokens ───────────────────────────────────────────────────────────────────
log "Detected endpoints — verify these match your host before applying:"
log "  LMIS_URL=$LMIS_URL  KC_URL=$KC_URL  DHIS2_URL=$DHIS2_URL"
log "  HAPI=$HAPI  LMIS_DB=$LMIS_DB"
log "Acquiring tokens ..."
LMIS_TOKEN=$(curl -sf -u user-client:changeme \
  -d "grant_type=password&username=admin&password=${LMIS_PASSWORD}" \
  "${LMIS_URL}/api/oauth/token" \
  | python3 -c "import sys,json;print(json.load(sys.stdin).get('access_token',''))" 2>/dev/null)
[[ -z "$LMIS_TOKEN" ]] && { log "ERROR: no OpenLMIS token — is the stack up on $LMIS_URL?"; exit 1; }
KC_TOKEN=$(curl -sf "${KC_URL}/auth/realms/master/protocol/openid-connect/token" \
  -d "grant_type=password&client_id=admin-cli&username=admin&password=${KC_ADMIN_PASSWORD}" \
  | python3 -c "import sys,json;print(json.load(sys.stdin).get('access_token',''))" 2>/dev/null)
[[ -z "$KC_TOKEN" ]] && log "WARN: no Keycloak token — user import will be skipped"

lmis_put()  { run "curl -sf -o /dev/null -X PUT '${LMIS_URL}$1' -H 'Authorization: Bearer ${LMIS_TOKEN}' -H 'Content-Type: application/json' -d '$2' || log '  WARN: LMIS PUT $1 failed'"; }
fhir_put()  { local code; if [[ "$DRY_RUN" == "1" ]]; then echo "  DRYRUN: fhir_put $1/$2"; return; fi; code=$(curl -s -o /dev/null -w '%{http_code}' -X PUT -H 'Content-Type: application/fhir+json' -d "$3" "${HAPI}/$1/$2"); [[ "$code" =~ ^2 ]] || log "  WARN: $1/$2 -> $code"; }

ADMIN_UUID=$(psqlc "SELECT id FROM referencedata.users WHERE username IN ('administrator','admin') ORDER BY username='administrator' DESC LIMIT 1;")

# ── 1. OpenLMIS: geo zone + facility types ───────────────────────────────────
log "OpenLMIS: Mafeteng geographic zone + facility types ..."
lmis_put "/api/geographicZones/${MFT_DISTRICT_GEOZONE}" \
  "{\"id\":\"${MFT_DISTRICT_GEOZONE}\",\"code\":\"MFT\",\"name\":\"${MFT_DISTRICT_NAME}\",\"level\":{\"id\":\"${GEO_LEVEL_DISTRICT_ID}\"},\"parent\":{\"id\":\"${GEO_ZONE_COUNTRY_ID}\"}}"
# ensure both facility types exist; capture their ids
psqlq "INSERT INTO referencedata.facility_types (id, active, code, name, displayorder)
       SELECT gen_random_uuid(), true, 'health_center', 'Health Center', 1
       WHERE NOT EXISTS (SELECT 1 FROM referencedata.facility_types WHERE lower(code)='health_center');
       INSERT INTO referencedata.facility_types (id, active, code, name, displayorder)
       SELECT gen_random_uuid(), true, 'hospital', 'Hospital', 2
       WHERE NOT EXISTS (SELECT 1 FROM referencedata.facility_types WHERE lower(code)='hospital');"
TYPE_HC=$(psqlc "SELECT id FROM referencedata.facility_types WHERE lower(code)='health_center' LIMIT 1;")
TYPE_HOSP=$(psqlc "SELECT id FROM referencedata.facility_types WHERE lower(code)='hospital' LIMIT 1;")
log "  type ids: health_center=$TYPE_HC hospital=$TYPE_HOSP"

# ── 2. Loop facilities → OpenLMIS facility + FHIR Org/Location + DHIS2 OU ─────
log "FHIR: Mafeteng district Location ..."
fhir_put Location "$MFT_DISTRICT_FHIRLOC" \
  "{\"resourceType\":\"Location\",\"id\":\"${MFT_DISTRICT_FHIRLOC}\",\"status\":\"active\",\"name\":\"${MFT_DISTRICT_NAME}\",\"mode\":\"instance\",\"physicalType\":{\"coding\":[{\"code\":\"jdn\",\"display\":\"Jurisdiction\"}]},\"address\":{\"district\":\"Mafeteng\",\"country\":\"LS\"}}"

DHIS2_OUS=""; FIDS=""
for row in "${MFT_FACILITIES[@]}"; do
  IFS='|' read -r NAME CODE FTYPE LMISID FHIRORG FHIRLOC DHOU <<< "$row"
  TYPE_ID=$TYPE_HC; [[ "$FTYPE" == "hospital" ]] && TYPE_ID=$TYPE_HOSP
  log "  facility: $NAME ($CODE, $FTYPE)"
  # OpenLMIS facility
  lmis_put "/api/facilities/${LMISID}" \
    "{\"id\":\"${LMISID}\",\"code\":\"${CODE}\",\"name\":\"${NAME}\",\"geographicZone\":{\"id\":\"${MFT_DISTRICT_GEOZONE}\"},\"type\":{\"id\":\"${TYPE_ID}\"},\"active\":true,\"enabled\":true,\"supportedPrograms\":[{\"id\":\"${PROGRAM_ID}\",\"supportActive\":true,\"supportLocallyFulfilled\":false}]}"
  FIDS="${FIDS}('${LMISID}'),"
  # FHIR Organization + Location
  fhir_put Organization "$FHIRORG" \
    "{\"resourceType\":\"Organization\",\"id\":\"${FHIRORG}\",\"active\":true,\"type\":[{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/organization-type\",\"code\":\"prov\",\"display\":\"Healthcare Provider\"}]}],\"name\":\"${NAME}\",\"address\":[{\"district\":\"Mafeteng\",\"country\":\"LS\"}]}"
  fhir_put Location "$FHIRLOC" \
    "{\"resourceType\":\"Location\",\"id\":\"${FHIRLOC}\",\"status\":\"active\",\"name\":\"${NAME}\",\"mode\":\"instance\",\"type\":[{\"coding\":[{\"system\":\"http://terminology.hl7.org/CodeSystem/v3-RoleCode\",\"code\":\"HC\",\"display\":\"Health Care\"}]}],\"physicalType\":{\"coding\":[{\"code\":\"bu\",\"display\":\"Building\"}]},\"partOf\":{\"reference\":\"Location/${MFT_DISTRICT_FHIRLOC}\"},\"managingOrganization\":{\"reference\":\"Organization/${FHIRORG}\"},\"address\":{\"district\":\"Mafeteng\",\"country\":\"LS\"}}"
  DHIS2_OUS="${DHIS2_OUS}{\"id\":\"${DHOU}\",\"name\":\"${NAME}\",\"shortName\":\"${NAME:0:48}\",\"openingDate\":\"2000-01-01\",\"parent\":{\"id\":\"${MFT_DISTRICT_DHIS2OU}\"}},"
done

# admin scoped stock rights at ALL facilities (batch — after every facility exists,
# so the FK is satisfied; right_assignments is read live, no service restart needed).
if [[ -n "$ADMIN_UUID" && -n "$FIDS" ]]; then
  log "OpenLMIS: granting admin stock rights (view/adjust/inventory) at all ${#MFT_FACILITIES[@]} facilities ..."
  psqlq "INSERT INTO referencedata.right_assignments (id, userid, rightname, facilityid, programid)
    SELECT gen_random_uuid(), '${ADMIN_UUID}', r.r, f.fid::uuid, '${PROGRAM_ID}'
    FROM (VALUES ('STOCK_ADJUST'),('STOCK_CARDS_VIEW'),('STOCK_INVENTORIES_EDIT')) r(r)
    CROSS JOIN (VALUES ${FIDS%,}) f(fid)
    WHERE NOT EXISTS (SELECT 1 FROM referencedata.right_assignments ra
      WHERE ra.userid='${ADMIN_UUID}' AND ra.rightname=r.r AND ra.facilityid=f.fid::uuid AND ra.programid='${PROGRAM_ID}');"
fi

# Supervisory access so the admin can SELECT the Mafeteng facilities in the OpenLMIS
# stock UI (the UI dropdown is driven by home + supervised facilities, not the rights
# cache): add them to the admin's Stock Supervisor requisition group, and move the
# admin's home facility off the now-inactive Maseru clinic onto a live Mafeteng one.
if [[ -n "$ADMIN_UUID" ]]; then
  SUP_RG=$(psqlc "SELECT rg.id FROM referencedata.requisition_groups rg
    JOIN referencedata.role_assignments ra ON ra.supervisorynodeid=rg.supervisorynodeid
    JOIN referencedata.roles r ON r.id=ra.roleid
    WHERE ra.userid='${ADMIN_UUID}' AND r.name='Stock Supervisor' LIMIT 1;")
  if [[ -n "$SUP_RG" ]]; then
    log "OpenLMIS: adding Mafeteng facilities to Stock Supervisor requisition group ..."
    psqlq "INSERT INTO referencedata.requisition_group_members (requisitiongroupid, facilityid)
      SELECT '${SUP_RG}', f.id FROM referencedata.facilities f
      WHERE f.geographiczoneid='${MFT_DISTRICT_GEOZONE}'
        AND NOT EXISTS (SELECT 1 FROM referencedata.requisition_group_members m
          WHERE m.requisitiongroupid='${SUP_RG}' AND m.facilityid=f.id);"
  fi
  psqlq "UPDATE referencedata.users SET homefacilityid=(SELECT id FROM referencedata.facilities WHERE code='MFT01')
         WHERE username IN ('admin','administrator');"
fi

# FHIR Practitioner per facility user — so the portal can link account status to
# Keycloak (mediator /users/status resolves practitionerId -> Practitioner ->
# http://keycloak/user-id identifier -> KC). id = kcId so it matches the mapping sourceId.
log "FHIR: Practitioner per facility user (Keycloak account-status link) ..."
for urow in "${MFT_USERS[@]}"; do
  IFS='|' read -r UNAME KCID UROLE _ _ <<< "$urow"
  fhir_put Practitioner "$KCID" \
    "{\"resourceType\":\"Practitioner\",\"id\":\"${KCID}\",\"active\":true,\"identifier\":[{\"system\":\"http://keycloak/user-id\",\"value\":\"${KCID}\"},{\"system\":\"http://keycloak/username\",\"value\":\"${UNAME}\"}],\"name\":[{\"use\":\"official\",\"text\":\"${UNAME}\"}]}"
done

# ── 3. DHIS2: district OU + facility OUs (one bulk metadata import) ───────────
log "DHIS2: Mafeteng district OU + ${#MFT_FACILITIES[@]} facility OUs ..."
run "curl -sf -o /dev/null -u admin:${DHIS2_PASSWORD} -X POST '${DHIS2_URL}/api/metadata?importStrategy=CREATE_AND_UPDATE&atomicMode=NONE' -H 'Content-Type: application/json' -d '{\"organisationUnits\":[{\"id\":\"${MFT_DISTRICT_DHIS2OU}\",\"name\":\"${MFT_DISTRICT_NAME}\",\"shortName\":\"Mafeteng\",\"openingDate\":\"1966-10-04\",\"parent\":{\"id\":\"${DHIS2_OU_NATIONAL}\"}},${DHIS2_OUS%,}]}' || log '  WARN: DHIS2 OU import failed'"

# ── 4. Keycloak: import the 36 facility users (partialImport, OVERWRITE) ──────
if [[ -n "${KC_TOKEN:-}" ]]; then
  log "Keycloak: importing facility coordinator users ..."
  # relative path so Windows-python and mingw-curl resolve the same file (avoid /tmp mismatch)
  # password injected from env (SEED_USER_PASSWORD) so it is never committed in the JSON
  SEED_USER_PASSWORD="${SEED_USER_PASSWORD:-changeme}" python3 -c "import json,os;u=json.load(open('config/facilities/mafeteng-realm-users.json'));pw=os.environ['SEED_USER_PASSWORD'];[c.__setitem__('value',pw) for usr in u for c in usr.get('credentials',[])];json.dump({'ifResourceExists':'OVERWRITE','users':u}, open('.mft-kc-users.json','w'))"
  run "curl -s -o /dev/null -w '  KC partialImport -> HTTP %{http_code}\n' -X POST '${KC_URL}/auth/admin/realms/opensrp/partialImport' -H 'Authorization: Bearer ${KC_TOKEN}' -H 'Content-Type: application/json' --data-binary @.mft-kc-users.json"
  rm -f .mft-kc-users.json
fi

# ── 5. Stock: seed SOH for the active demo orderables at every facility ───────
RR=$(psqlc "SELECT id FROM stockmanagement.stock_card_line_item_reasons WHERE name='Receipts' LIMIT 1;")
# orderableId|lotId for each active orderable, reusing the existing global per-medicine
# batches (AMOX-LOT-2026 etc.) so SOH is tracked by lot/expiry (FEFO). lotId is blank if
# a medicine has no lot — those lines fall back to lot-less stock.
OID_LOTS=$(docker exec "$LMIS_DB" psql -U postgres -d open_lmis -tA -F'|' -c "
  SELECT DISTINCT o.id, COALESCE(l.id::text,'')
  FROM referencedata.orderables o
  LEFT JOIN referencedata.orderable_identifiers oi ON oi.orderableid=o.id AND oi.key='tradeItem'
  LEFT JOIN referencedata.lots l ON l.tradeitemid::text = oi.value
  WHERE o.id IN (SELECT orderableid FROM referencedata.facility_type_approved_products
                 WHERE programid='${PROGRAM_ID}' AND active=true);" 2>/dev/null)
if [[ -n "$RR" && -n "$OID_LOTS" ]]; then
  log "Stock: seeding ${STOCK_QTY} units (lot-tracked) of active orderables at each facility ..."
  for row in "${MFT_FACILITIES[@]}"; do
    IFS='|' read -r NAME CODE FTYPE LMISID _ _ _ <<< "$row"
    # idempotent: skip a facility that already has stock for the program (avoid double-seeding)
    HAVE=$(psqlc "SELECT count(*) FROM stockmanagement.stock_cards WHERE facilityid='${LMISID}' AND programid='${PROGRAM_ID}';")
    if [[ "${HAVE:-0}" != "0" ]]; then log "  ${NAME}: already has stock — skipping"; continue; fi
    LINES=""
    while IFS='|' read -r oid lotid; do
      [[ -z "$oid" ]] && continue
      LOTF=""; [[ -n "$lotid" ]] && LOTF="\"lotId\":\"${lotid}\","
      LINES="${LINES}{\"orderableId\":\"${oid}\",${LOTF}\"quantity\":${STOCK_QTY},\"occurredDate\":\"${TODAY}\",\"reasonId\":\"${RR}\",\"documentationNo\":\"RESEED-MFT\"},"
    done <<< "$OID_LOTS"
    run "curl -sf -o /dev/null -X POST -H 'Authorization: Bearer ${LMIS_TOKEN}' -H 'Content-Type: application/json' '${LMIS_URL}/api/stockEvents' -d '{\"facilityId\":\"${LMISID}\",\"programId\":\"${PROGRAM_ID}\",\"lineItems\":[${LINES%,}]}' || log '  WARN: stock event failed at ${NAME}'"
  done
else
  log "WARN: no Receipts reason or no active orderables — stock not seeded."
fi

# ── 6. Apply derived configs (mediator mappings + bkm-web OU_LABELS) ──────────
log "Applying mediator mappings (merge: keep medications, replace performers) ..."
if [[ "$DRY_RUN" != "1" ]]; then
  python3 - <<'PY'
import json
new=json.load(open('config/facilities/mafeteng-mappings.json'))
try: cur=json.load(open('mediator/mappings.json'))
except Exception: cur={}
out={'performers':new['performers'],'medications':cur.get('medications',[])}
json.dump(out, open('mediator/mappings.json','w'), indent=2)
print(f"  mappings.json: {len(out['performers'])} performers, {len(out['medications'])} medications")
PY
  # splice OU_LABELS into bkm-web/js/core.js
  python3 - <<'PY'
import re
block=open('config/facilities/mafeteng-ou-labels.js').read()
m=re.sub(r'^//[^\n]*\n','',block).strip()
src=open('bkm-web/js/core.js').read()
new=re.sub(r'var OU_LABELS = \{.*?\n\};', m, src, count=1, flags=re.S)
open('bkm-web/js/core.js','w').write(new)
print("  core.js OU_LABELS replaced with Mafeteng OUs")
PY
fi

# ── 7. Deactivate Maseru demo facilities (optional) ──────────────────────────
if [[ "$REMOVE_MASERU" == "1" ]]; then
  log "Deactivating Maseru demo facilities in OpenLMIS ..."
  psqlq "UPDATE referencedata.facilities SET active=false, enabled=false WHERE code IN ('MDA','MC-A','MC-B','MDB');"
fi

log "Restarting mediator to reload mappings ..."
run "docker compose restart bkm-mediator >/dev/null 2>&1 || true"
log "DONE. ${#MFT_FACILITIES[@]} facilities, ${#MFT_USERS[@]} users. DRY_RUN=${DRY_RUN} REMOVE_MASERU=${REMOVE_MASERU}"
log "Verify: OpenLMIS facilities list, FHIR Location?partof=${MFT_DISTRICT_FHIRLOC}, KC users sm.* / co.*, bkm-web #/orders scoping."
