FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html config.js style.css favicon.svg lesotho-flag.jpg oip.webp image.png /usr/share/nginx/html/
COPY js/ /usr/share/nginx/html/js/
